[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
egui = "0.33.0"
rand = "0.9.2"
image = { version = "0.24", default-features = false, features = ["png"] }

[package.metadata]
default_fonts = true